bedrock:
  address: "0.0.0.0"
  port: 19132
  clone-remote-port: false
  motd1: "GeyserMC"
  motd2: "Another GeyserMC forced host."
  server-name: "A bedrock-enabled Server"
remote:
  address: 127.0.0.1
  port: 25565
  auth-type: online
  forward-hostname: true
command-suggestions: true
passthrough-motd: true
passthrough-protocol-name: false
passthrough-player-counts: true
legacy-ping-passthrough: false
ping-passthrough: false
ping-passthrough-interval: 3
forward-player-ping: true
max-players: "100"
debug-mode: false
general-thread-pool: "32"
allow-third-party-capes: true
allow-third-party-ears: true
cache-chunks: false
cache-images: "0"
above-bedrock-nether-building: true
force-resource-packs: true
metrics:
  enabled: false
  uuid: "generateduuid"